package inventorymanagementsystem;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Patrick Larocque
 */

public class Customer extends javax.swing.JFrame {

    public Customer() {
        initComponents();
        displayCustomers();
    }
    
    Connection connection = null;
    Statement statement = null;
    ResultSet results = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerPanel = new javax.swing.JPanel();
        customerTopPanel = new javax.swing.JPanel();
        customerTitle = new javax.swing.JLabel();
        customerHeader = new javax.swing.JLabel();
        customerBottomPanel = new javax.swing.JPanel();
        customerCredits = new javax.swing.JLabel();
        customerBrand = new javax.swing.JLabel();
        customerTablePanel = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        customerList = new javax.swing.JLabel();
        customerID = new javax.swing.JLabel();
        customerName = new javax.swing.JLabel();
        customerPhone = new javax.swing.JLabel();
        customerAddButton = new javax.swing.JButton();
        customerEditButton = new javax.swing.JButton();
        customerDeleteButton = new javax.swing.JButton();
        customerMainMenuButton = new javax.swing.JButton();
        customerIDField = new javax.swing.JTextField();
        customerNameField = new javax.swing.JTextField();
        customerPhoneField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerTopPanel.setBackground(new java.awt.Color(66, 68, 74));

        customerTitle.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        customerTitle.setForeground(new java.awt.Color(255, 255, 255));
        customerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerTitle.setText("Customer Menu");

        customerHeader.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        customerHeader.setForeground(new java.awt.Color(255, 255, 255));
        customerHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerHeader.setText("Inventory Management System");

        javax.swing.GroupLayout customerTopPanelLayout = new javax.swing.GroupLayout(customerTopPanel);
        customerTopPanel.setLayout(customerTopPanelLayout);
        customerTopPanelLayout.setHorizontalGroup(
            customerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerTopPanelLayout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addGroup(customerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerTopPanelLayout.createSequentialGroup()
                        .addComponent(customerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(489, 489, 489))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerTopPanelLayout.createSequentialGroup()
                        .addComponent(customerHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 266, 266))))
        );
        customerTopPanelLayout.setVerticalGroup(
            customerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerTopPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(customerHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerTitle)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        customerBottomPanel.setBackground(new java.awt.Color(66, 68, 74));

        customerCredits.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        customerCredits.setForeground(new java.awt.Color(255, 255, 255));
        customerCredits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerCredits.setText("Software by Patrick");

        customerBrand.setFont(new java.awt.Font("OCR A Extended", 1, 28)); // NOI18N
        customerBrand.setForeground(new java.awt.Color(255, 255, 255));
        customerBrand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerBrand.setText("invSYS");

        javax.swing.GroupLayout customerBottomPanelLayout = new javax.swing.GroupLayout(customerBottomPanel);
        customerBottomPanel.setLayout(customerBottomPanelLayout);
        customerBottomPanelLayout.setHorizontalGroup(
            customerBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerBottomPanelLayout.createSequentialGroup()
                .addGroup(customerBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerBottomPanelLayout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(customerCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerBottomPanelLayout.createSequentialGroup()
                        .addGap(493, 493, 493)
                        .addComponent(customerBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customerBottomPanelLayout.setVerticalGroup(
            customerBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerBottomPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(customerBrand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        customerTable.setFont(new java.awt.Font("Cascadia Code", 0, 16)); // NOI18N
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Phone"
            }
        ));
        customerTable.setRowHeight(25);
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        customerTablePanel.setViewportView(customerTable);

        customerList.setFont(new java.awt.Font("Cascadia Code", 1, 20)); // NOI18N
        customerList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerList.setText("Customer List");

        customerID.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        customerID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerID.setText("Customer ID");

        customerName.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        customerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerName.setText("Name");

        customerPhone.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        customerPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerPhone.setText("Phone");

        customerAddButton.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        customerAddButton.setText("Add");
        customerAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerAddButtonMouseClicked(evt);
            }
        });
        customerAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerAddButtonActionPerformed(evt);
            }
        });

        customerEditButton.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        customerEditButton.setText("Edit");
        customerEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerEditButtonMouseClicked(evt);
            }
        });
        customerEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerEditButtonActionPerformed(evt);
            }
        });

        customerDeleteButton.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        customerDeleteButton.setText("Delete");
        customerDeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerDeleteButtonMouseClicked(evt);
            }
        });
        customerDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerDeleteButtonActionPerformed(evt);
            }
        });

        customerMainMenuButton.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        customerMainMenuButton.setText("Main Menu");
        customerMainMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerMainMenuButtonMouseClicked(evt);
            }
        });
        customerMainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerMainMenuButtonActionPerformed(evt);
            }
        });

        customerIDField.setFont(new java.awt.Font("Cascadia Code", 0, 16)); // NOI18N
        customerIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIDFieldActionPerformed(evt);
            }
        });

        customerNameField.setFont(new java.awt.Font("Cascadia Code", 0, 16)); // NOI18N
        customerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameFieldActionPerformed(evt);
            }
        });

        customerPhoneField.setFont(new java.awt.Font("Cascadia Code", 0, 16)); // NOI18N
        customerPhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerPhoneFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(customerBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerID, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerPhoneField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(customerAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(customerEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(customerDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(customerMainMenuButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                        .addComponent(customerTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                        .addComponent(customerList, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233))))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addComponent(customerTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customerList)
                .addGap(18, 18, 18)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addComponent(customerTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(customerMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addComponent(customerBottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customerAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerAddButtonActionPerformed

    private void customerEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerEditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerEditButtonActionPerformed

    private void customerDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerDeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerDeleteButtonActionPerformed

    private void customerMainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerMainMenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerMainMenuButtonActionPerformed

    private void customerIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIDFieldActionPerformed

    private void customerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameFieldActionPerformed

    private void customerPhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerPhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerPhoneFieldActionPerformed

    private void customerAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerAddButtonMouseClicked
        try {
            connection = DriverManager.getConnection("jdbc:derby://localhost:1527/InventoryDB", "sa", "admin");
            PreparedStatement add = connection.prepareStatement("INSERT into CUSTOMER VALUES (?, ?, ?)");
            add.setInt(1, Integer.valueOf(customerIDField.getText()));
            add.setString(2, customerNameField.getText());
            add.setString(3, customerPhoneField.getText());
            int row = add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Customer sucessfully added.");
            connection.close();
            displayCustomers();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_customerAddButtonMouseClicked

    private void customerDeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerDeleteButtonMouseClicked
        if (customerIDField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter a customer to be deleted.");
        } else {
            try {
                connection = DriverManager.getConnection("jdbc:derby://localhost:1527/InventoryDB", "sa", "admin");
                String id = customerIDField.getText();
                String query = "DELETE from SA.CUSTOMER where Customer_ID = " + id;
                Statement add = connection.createStatement();
                add.executeUpdate(query);
                displayCustomers();
                JOptionPane.showMessageDialog(this, "Customer sucessfully deleted.");
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_customerDeleteButtonMouseClicked

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)customerTable.getModel();
        int index = customerTable.getSelectedRow();
        customerIDField.setText(model.getValueAt(index, 0).toString());
        customerNameField.setText(model.getValueAt(index, 1).toString());
        customerPhoneField.setText(model.getValueAt(index, 2).toString());
    }//GEN-LAST:event_customerTableMouseClicked

    private void customerEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerEditButtonMouseClicked
        if (customerIDField.getText().isEmpty() || customerNameField.getText().isEmpty() || customerPhoneField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information. Please fill out all required fields.");
        } else {
            try {
                connection = DriverManager.getConnection("jdbc:derby://localhost:1527/InventoryDB", "sa", "admin");
                String updateQuery = "UPDATE SA.CUSTOMER SET Customer_Name = '" + customerNameField.getText() + "', Customer_Phone = '" + customerPhoneField.getText() + "' WHERE Customer_ID = " + customerIDField.getText();
                Statement add = connection.createStatement();
                add.executeUpdate(updateQuery);
                JOptionPane.showMessageDialog(this, "Customers sucessfully modified.");
                displayCustomers();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }    
    }//GEN-LAST:event_customerEditButtonMouseClicked

    private void customerMainMenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerMainMenuButtonMouseClicked
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerMainMenuButtonMouseClicked

    public void displayCustomers() {
        try {
            connection = DriverManager.getConnection("jdbc:derby://localhost:1527/InventoryDB", "sa", "admin");
            statement = connection.createStatement();
            results = statement.executeQuery("SELECT * FROM CUSTOMER");
            customerTable.setModel(DbUtils.resultSetToTableModel(results));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerAddButton;
    private javax.swing.JPanel customerBottomPanel;
    private javax.swing.JLabel customerBrand;
    private javax.swing.JLabel customerCredits;
    private javax.swing.JButton customerDeleteButton;
    private javax.swing.JButton customerEditButton;
    private javax.swing.JLabel customerHeader;
    private javax.swing.JLabel customerID;
    private javax.swing.JTextField customerIDField;
    private javax.swing.JLabel customerList;
    private javax.swing.JButton customerMainMenuButton;
    private javax.swing.JLabel customerName;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JLabel customerPhone;
    private javax.swing.JTextField customerPhoneField;
    private javax.swing.JTable customerTable;
    private javax.swing.JScrollPane customerTablePanel;
    private javax.swing.JLabel customerTitle;
    private javax.swing.JPanel customerTopPanel;
    // End of variables declaration//GEN-END:variables
}
