package inventorymanagementsystem;

/**
 *
 * @author Patrick Larocque
 */
public class MainMenu extends javax.swing.JFrame {

    public MainMenu() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainBottomPanel = new javax.swing.JPanel();
        mainCredits = new javax.swing.JLabel();
        mainBrand = new javax.swing.JLabel();
        mainTopPanel = new javax.swing.JPanel();
        mainTitle = new javax.swing.JLabel();
        mainHeader = new javax.swing.JLabel();
        mainProductsPanel = new javax.swing.JPanel();
        mainProducts = new javax.swing.JLabel();
        mainProductsIcon = new javax.swing.JLabel();
        mainCustomersPanel = new javax.swing.JPanel();
        mainCustomers = new javax.swing.JLabel();
        mainCustomersIcon = new javax.swing.JLabel();
        mainCategoriesPanel = new javax.swing.JPanel();
        mainCategories = new javax.swing.JLabel();
        mainCategoriesIcon = new javax.swing.JLabel();
        mainUsersPanel = new javax.swing.JPanel();
        mainUsers = new javax.swing.JLabel();
        mainUsersIcon = new javax.swing.JLabel();
        mainOrdersPanel = new javax.swing.JPanel();
        mainOrders = new javax.swing.JLabel();
        mainOrdersIcon = new javax.swing.JLabel();
        mainLogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainBottomPanel.setBackground(new java.awt.Color(66, 68, 74));

        mainCredits.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        mainCredits.setForeground(new java.awt.Color(255, 255, 255));
        mainCredits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainCredits.setText("Software by Patrick");

        mainBrand.setFont(new java.awt.Font("OCR A Extended", 1, 28)); // NOI18N
        mainBrand.setForeground(new java.awt.Color(255, 255, 255));
        mainBrand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainBrand.setText("invSYS");

        javax.swing.GroupLayout mainBottomPanelLayout = new javax.swing.GroupLayout(mainBottomPanel);
        mainBottomPanel.setLayout(mainBottomPanelLayout);
        mainBottomPanelLayout.setHorizontalGroup(
            mainBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBottomPanelLayout.createSequentialGroup()
                .addGroup(mainBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainBottomPanelLayout.createSequentialGroup()
                        .addGap(459, 459, 459)
                        .addComponent(mainBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainBottomPanelLayout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(mainCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainBottomPanelLayout.setVerticalGroup(
            mainBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBottomPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(mainBrand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        mainTopPanel.setBackground(new java.awt.Color(66, 68, 74));

        mainTitle.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(255, 255, 255));
        mainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitle.setText("Main Menu");

        mainHeader.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        mainHeader.setForeground(new java.awt.Color(255, 255, 255));
        mainHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainHeader.setText("Inventory Management System");

        javax.swing.GroupLayout mainTopPanelLayout = new javax.swing.GroupLayout(mainTopPanel);
        mainTopPanel.setLayout(mainTopPanelLayout);
        mainTopPanelLayout.setHorizontalGroup(
            mainTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainTopPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
            .addGroup(mainTopPanelLayout.createSequentialGroup()
                .addGap(453, 453, 453)
                .addComponent(mainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainTopPanelLayout.setVerticalGroup(
            mainTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainTopPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(mainHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainTitle)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        mainProductsPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainProductsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainProductsPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainProductsPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainProductsPanelMouseReleased(evt);
            }
        });

        mainProducts.setFont(new java.awt.Font("Cascadia Code", 0, 22)); // NOI18N
        mainProducts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainProducts.setText("Products");

        mainProductsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainProductsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementsystem/Assets/product.png"))); // NOI18N

        javax.swing.GroupLayout mainProductsPanelLayout = new javax.swing.GroupLayout(mainProductsPanel);
        mainProductsPanel.setLayout(mainProductsPanelLayout);
        mainProductsPanelLayout.setHorizontalGroup(
            mainProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainProductsPanelLayout.createSequentialGroup()
                .addGroup(mainProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainProductsPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(mainProductsIcon))
                    .addGroup(mainProductsPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(mainProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainProductsPanelLayout.setVerticalGroup(
            mainProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainProductsPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(mainProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainProductsIcon)
                .addGap(39, 39, 39))
        );

        mainCustomersPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainCustomersPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainCustomersPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainCustomersPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainCustomersPanelMouseReleased(evt);
            }
        });

        mainCustomers.setFont(new java.awt.Font("Cascadia Code", 0, 22)); // NOI18N
        mainCustomers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainCustomers.setText("Customers");

        mainCustomersIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainCustomersIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementsystem/Assets/customer.png"))); // NOI18N

        javax.swing.GroupLayout mainCustomersPanelLayout = new javax.swing.GroupLayout(mainCustomersPanel);
        mainCustomersPanel.setLayout(mainCustomersPanelLayout);
        mainCustomersPanelLayout.setHorizontalGroup(
            mainCustomersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainCustomersPanelLayout.createSequentialGroup()
                .addGroup(mainCustomersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainCustomersPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(mainCustomersIcon))
                    .addGroup(mainCustomersPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(mainCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainCustomersPanelLayout.setVerticalGroup(
            mainCustomersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainCustomersPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(mainCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainCustomersIcon)
                .addGap(39, 39, 39))
        );

        mainCategoriesPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainCategoriesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainCategoriesPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainCategoriesPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainCategoriesPanelMouseReleased(evt);
            }
        });

        mainCategories.setFont(new java.awt.Font("Cascadia Code", 0, 22)); // NOI18N
        mainCategories.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainCategories.setText("Categories");

        mainCategoriesIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainCategoriesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementsystem/Assets/categories.png"))); // NOI18N

        javax.swing.GroupLayout mainCategoriesPanelLayout = new javax.swing.GroupLayout(mainCategoriesPanel);
        mainCategoriesPanel.setLayout(mainCategoriesPanelLayout);
        mainCategoriesPanelLayout.setHorizontalGroup(
            mainCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainCategoriesPanelLayout.createSequentialGroup()
                .addGroup(mainCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainCategoriesPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(mainCategoriesIcon))
                    .addGroup(mainCategoriesPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(mainCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainCategoriesPanelLayout.setVerticalGroup(
            mainCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainCategoriesPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(mainCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainCategoriesIcon)
                .addGap(39, 39, 39))
        );

        mainUsersPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainUsersPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainUsersPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainUsersPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainUsersPanelMouseReleased(evt);
            }
        });

        mainUsers.setFont(new java.awt.Font("Cascadia Code", 0, 22)); // NOI18N
        mainUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainUsers.setText("Users");

        mainUsersIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainUsersIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementsystem/Assets/users.png"))); // NOI18N

        javax.swing.GroupLayout mainUsersPanelLayout = new javax.swing.GroupLayout(mainUsersPanel);
        mainUsersPanel.setLayout(mainUsersPanelLayout);
        mainUsersPanelLayout.setHorizontalGroup(
            mainUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainUsersPanelLayout.createSequentialGroup()
                .addGroup(mainUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainUsersPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(mainUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainUsersPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(mainUsersIcon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainUsersPanelLayout.setVerticalGroup(
            mainUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainUsersPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(mainUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainUsersIcon)
                .addGap(39, 39, 39))
        );

        mainOrdersPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainOrdersPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainOrdersPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainOrdersPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainOrdersPanelMouseReleased(evt);
            }
        });

        mainOrders.setFont(new java.awt.Font("Cascadia Code", 0, 22)); // NOI18N
        mainOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainOrders.setText("Orders");

        mainOrdersIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainOrdersIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementsystem/Assets/order.png"))); // NOI18N

        javax.swing.GroupLayout mainOrdersPanelLayout = new javax.swing.GroupLayout(mainOrdersPanel);
        mainOrdersPanel.setLayout(mainOrdersPanelLayout);
        mainOrdersPanelLayout.setHorizontalGroup(
            mainOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainOrdersPanelLayout.createSequentialGroup()
                .addGroup(mainOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainOrdersPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(mainOrdersIcon))
                    .addGroup(mainOrdersPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(mainOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        mainOrdersPanelLayout.setVerticalGroup(
            mainOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainOrdersPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(mainOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainOrdersIcon)
                .addGap(39, 39, 39))
        );

        mainLogoutButton.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        mainLogoutButton.setText("Logout");
        mainLogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainLogoutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(mainProductsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(mainCustomersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(mainCategoriesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainUsersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainOrdersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainLogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(473, 473, 473))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addComponent(mainTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainCustomersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainCategoriesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainOrdersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainUsersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainProductsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(mainLogoutButton)
                .addGap(49, 49, 49)
                .addComponent(mainBottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mainProductsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainProductsPanelMouseClicked
        new Product().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainProductsPanelMouseClicked

    private void mainProductsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainProductsPanelMousePressed
        mainProductsPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }//GEN-LAST:event_mainProductsPanelMousePressed

    private void mainCategoriesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainCategoriesPanelMouseClicked
        new Categories().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainCategoriesPanelMouseClicked

    private void mainCategoriesPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainCategoriesPanelMousePressed
        mainCategoriesPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }//GEN-LAST:event_mainCategoriesPanelMousePressed

    private void mainProductsPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainProductsPanelMouseReleased
        mainProductsPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_mainProductsPanelMouseReleased

    private void mainCategoriesPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainCategoriesPanelMouseReleased
        mainCategoriesPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_mainCategoriesPanelMouseReleased

    private void mainCustomersPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainCustomersPanelMouseClicked
        new Customer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainCustomersPanelMouseClicked

    private void mainCustomersPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainCustomersPanelMousePressed
        mainCustomersPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }//GEN-LAST:event_mainCustomersPanelMousePressed

    private void mainCustomersPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainCustomersPanelMouseReleased
        mainCustomersPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_mainCustomersPanelMouseReleased

    private void mainUsersPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainUsersPanelMouseClicked
        new User().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainUsersPanelMouseClicked

    private void mainUsersPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainUsersPanelMousePressed
        mainUsersPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }//GEN-LAST:event_mainUsersPanelMousePressed

    private void mainUsersPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainUsersPanelMouseReleased
        mainUsersPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_mainUsersPanelMouseReleased

    private void mainOrdersPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainOrdersPanelMouseClicked
        new Order().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainOrdersPanelMouseClicked

    private void mainOrdersPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainOrdersPanelMousePressed
        mainOrdersPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }//GEN-LAST:event_mainOrdersPanelMousePressed

    private void mainOrdersPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainOrdersPanelMouseReleased
        mainOrdersPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_mainOrdersPanelMouseReleased

    private void mainLogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainLogoutButtonMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainLogoutButtonMouseClicked

    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainBottomPanel;
    private javax.swing.JLabel mainBrand;
    private javax.swing.JLabel mainCategories;
    private javax.swing.JLabel mainCategoriesIcon;
    private javax.swing.JPanel mainCategoriesPanel;
    private javax.swing.JLabel mainCredits;
    private javax.swing.JLabel mainCustomers;
    private javax.swing.JLabel mainCustomersIcon;
    private javax.swing.JPanel mainCustomersPanel;
    private javax.swing.JLabel mainHeader;
    private javax.swing.JButton mainLogoutButton;
    private javax.swing.JLabel mainOrders;
    private javax.swing.JLabel mainOrdersIcon;
    private javax.swing.JPanel mainOrdersPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mainProducts;
    private javax.swing.JLabel mainProductsIcon;
    private javax.swing.JPanel mainProductsPanel;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JPanel mainTopPanel;
    private javax.swing.JLabel mainUsers;
    private javax.swing.JLabel mainUsersIcon;
    private javax.swing.JPanel mainUsersPanel;
    // End of variables declaration//GEN-END:variables
}