package inventorymanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Patrick Larocque
 */

public class User extends javax.swing.JFrame {

    public User() {
        initComponents();
        displayUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    Connection connection = null;
    Statement statement = null;
    ResultSet results = null;
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPanel = new javax.swing.JPanel();
        userTopPanel = new javax.swing.JPanel();
        userTitle = new javax.swing.JLabel();
        userHeader = new javax.swing.JLabel();
        userBottomPanel = new javax.swing.JPanel();
        userCredits = new javax.swing.JLabel();
        userBrand = new javax.swing.JLabel();
        userMainMenuButton = new javax.swing.JButton();
        userTablePanel = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        userList = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        userPassword = new javax.swing.JLabel();
        userPhone = new javax.swing.JLabel();
        userAddButton = new javax.swing.JButton();
        userUpdateButton = new javax.swing.JButton();
        userDeleteButton = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        userPasswordField = new javax.swing.JTextField();
        userPhoneField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userTopPanel.setBackground(new java.awt.Color(66, 68, 74));

        userTitle.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        userTitle.setForeground(new java.awt.Color(255, 255, 255));
        userTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userTitle.setText("User Menu");

        userHeader.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        userHeader.setForeground(new java.awt.Color(255, 255, 255));
        userHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userHeader.setText("Inventory Management System");

        javax.swing.GroupLayout userTopPanelLayout = new javax.swing.GroupLayout(userTopPanel);
        userTopPanel.setLayout(userTopPanelLayout);
        userTopPanelLayout.setHorizontalGroup(
            userTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTopPanelLayout.createSequentialGroup()
                .addGroup(userTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userTopPanelLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(userHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userTopPanelLayout.createSequentialGroup()
                        .addGap(539, 539, 539)
                        .addComponent(userTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userTopPanelLayout.setVerticalGroup(
            userTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTopPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(userHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTitle)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        userBottomPanel.setBackground(new java.awt.Color(66, 68, 74));

        userCredits.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        userCredits.setForeground(new java.awt.Color(255, 255, 255));
        userCredits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCredits.setText("Software by Patrick");

        userBrand.setFont(new java.awt.Font("OCR A Extended", 1, 28)); // NOI18N
        userBrand.setForeground(new java.awt.Color(255, 255, 255));
        userBrand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userBrand.setText("invSYS");

        userMainMenuButton.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        userMainMenuButton.setText("Main Menu");
        userMainMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMainMenuButtonMouseClicked(evt);
            }
        });
        userMainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMainMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userBottomPanelLayout = new javax.swing.GroupLayout(userBottomPanel);
        userBottomPanel.setLayout(userBottomPanelLayout);
        userBottomPanelLayout.setHorizontalGroup(
            userBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userBottomPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userBottomPanelLayout.createSequentialGroup()
                        .addComponent(userCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userBottomPanelLayout.createSequentialGroup()
                        .addComponent(userBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(430, 430, 430)))
                .addComponent(userMainMenuButton)
                .addGap(49, 49, 49))
        );
        userBottomPanelLayout.setVerticalGroup(
            userBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userBottomPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(userBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userBottomPanelLayout.createSequentialGroup()
                        .addComponent(userBrand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userBottomPanelLayout.createSequentialGroup()
                        .addComponent(userMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        userTable.setFont(new java.awt.Font("Cascadia Code", 0, 16)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Phone"
            }
        ));
        userTable.setRowHeight(25);
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        userTablePanel.setViewportView(userTable);

        userList.setFont(new java.awt.Font("Cascadia Code", 1, 20)); // NOI18N
        userList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userList.setText("User List");

        username.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Username");

        userPassword.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        userPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userPassword.setText("Password");

        userPhone.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        userPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userPhone.setText("Phone");

        userAddButton.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        userAddButton.setText("Add");
        userAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userAddButtonMouseClicked(evt);
            }
        });
        userAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAddButtonActionPerformed(evt);
            }
        });

        userUpdateButton.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        userUpdateButton.setText("Update");
        userUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userUpdateButtonMouseClicked(evt);
            }
        });
        userUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userUpdateButtonActionPerformed(evt);
            }
        });

        userDeleteButton.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        userDeleteButton.setText("Delete");
        userDeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userDeleteButtonMouseClicked(evt);
            }
        });
        userDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDeleteButtonActionPerformed(evt);
            }
        });

        usernameField.setFont(new java.awt.Font("Cascadia Code", 0, 16)); // NOI18N
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        userPasswordField.setFont(new java.awt.Font("Cascadia Code", 0, 16)); // NOI18N
        userPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPasswordFieldActionPerformed(evt);
            }
        });

        userPhoneField.setFont(new java.awt.Font("Cascadia Code", 0, 16)); // NOI18N
        userPhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPhoneFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userPhoneField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(userAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(userUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(userDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(userTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(userList, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addComponent(userTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userList)
                .addGap(18, 18, 18)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addComponent(userTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)))
                .addComponent(userBottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userAddButtonActionPerformed

    private void userUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userUpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userUpdateButtonActionPerformed

    private void userDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userDeleteButtonActionPerformed

    private void userMainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMainMenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userMainMenuButtonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void userPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPasswordFieldActionPerformed

    private void userPhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPhoneFieldActionPerformed

    private void userAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userAddButtonMouseClicked
        try {
            connection = DriverManager.getConnection("jdbc:derby://localhost:1527/InventoryDB", "sa", "admin");
            PreparedStatement add = connection.prepareStatement("INSERT into USERS VALUES (?, ?, ?)");
            add.setString(1, usernameField.getText());
            add.setString(2, userPasswordField.getText());
            add.setString(3, userPhoneField.getText());
            int row = add.executeUpdate();
            JOptionPane.showMessageDialog(this, "User sucessfully added.");
            connection.close();
            displayUsers();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }       
    }//GEN-LAST:event_userAddButtonMouseClicked

    private void userDeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDeleteButtonMouseClicked
        if (usernameField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter a user to be deleted.");
        } else {
            try {
                connection = DriverManager.getConnection("jdbc:derby://localhost:1527/InventoryDB", "sa", "admin");
                String id = usernameField.getText();
                String query = "DELETE from SA.USERS where User_Name = '" + id + "'";
                Statement add = connection.createStatement();
                add.executeUpdate(query);
                displayUsers();
                JOptionPane.showMessageDialog(this, "User sucessfully deleted.");
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_userDeleteButtonMouseClicked

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)userTable.getModel();
        int index = userTable.getSelectedRow();
        usernameField.setText(model.getValueAt(index, 0).toString());
        userPasswordField.setText(model.getValueAt(index, 1).toString());
        userPhoneField.setText(model.getValueAt(index, 2).toString());
    }//GEN-LAST:event_userTableMouseClicked

    private void userUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userUpdateButtonMouseClicked
        if (usernameField.getText().isEmpty() || userPasswordField.getText().isEmpty() || userPhoneField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information. Please fill out all required fields.");
        } else {
            try {
                connection = DriverManager.getConnection("jdbc:derby://localhost:1527/InventoryDB", "sa", "admin");
                String updateQuery = "UPDATE SA.USERS SET User_Password = '" + userPasswordField.getText() + "', User_Phone = '" + userPhoneField.getText() + "' WHERE User_Name = '" + usernameField.getText() + "'";
                Statement add = connection.createStatement();
                add.executeUpdate(updateQuery);
                JOptionPane.showMessageDialog(this, "User information sucessfully updated.");
                displayUsers();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }  
    }//GEN-LAST:event_userUpdateButtonMouseClicked

    private void userMainMenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMainMenuButtonMouseClicked
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userMainMenuButtonMouseClicked

    public void displayUsers() {
        try {
            connection = DriverManager.getConnection("jdbc:derby://localhost:1527/InventoryDB", "sa", "admin");
            statement = connection.createStatement();
            results = statement.executeQuery("SELECT * FROM USERS");
            userTable.setModel(DbUtils.resultSetToTableModel(results));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton userAddButton;
    private javax.swing.JPanel userBottomPanel;
    private javax.swing.JLabel userBrand;
    private javax.swing.JLabel userCredits;
    private javax.swing.JButton userDeleteButton;
    private javax.swing.JLabel userHeader;
    private javax.swing.JLabel userList;
    private javax.swing.JButton userMainMenuButton;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel userPassword;
    private javax.swing.JTextField userPasswordField;
    private javax.swing.JLabel userPhone;
    private javax.swing.JTextField userPhoneField;
    private javax.swing.JTable userTable;
    private javax.swing.JScrollPane userTablePanel;
    private javax.swing.JLabel userTitle;
    private javax.swing.JPanel userTopPanel;
    private javax.swing.JButton userUpdateButton;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}